repos:
  - repo: local
    hooks:
      - id: nixpkgs-fmt
        name: nixpkgs-fmt
        entry: nixpkgs-fmt
        language: system
        files: '\.nix$'
      - id: prettier
        name: prettier
        entry: prettier --write --list-different --ignore-unknown
        language: system
        files: ""
        exclude: 'pnpm-lock\.yaml'
